= Assign Content Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-assign-content/master["Build status", link="https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-assign-content/master/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

[cols="^2,^2,^2,^2",options="header"]
|===
|onRequest|onResponse|onRequestContent|onResponseContent

|-
|-
|X
|X

|===

== Description

The `assign content` policy is used to change and / or transform the content of the request body or response body.

This policy is compatible with https://freemarker.apache.org[Freemarker] template engine which allows you to apply
complex transformation like moving from XML to JSON and vice-versa.

[source, json]
.Incoming request body content
----
{
  "symbol": "EUR"
}
----

[source, xml]
.Policy example to transform from json to xml
----
<#assign body = request.content?eval >
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webserviceX.NET/">
   <soapenv:Header/>
   <soapenv:Body>
      <web:GetQuote>
         ${body.symbol}
      </web:GetQuote>
   </soapenv:Body>
</soapenv:Envelope>
----

[source, xml]
.Expected output
----
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:web="http://www.webserviceX.NET/">
 <soapenv:Header/>
 <soapenv:Body>
 <web:GetQuote>
 EUR
 </web:GetQuote>
 </soapenv:Body>
</soapenv:Envelope>
----

== Configuration

|===
|Property |Required |Description |Type |Default

.^|scope
^.^|X
|The scope for which the policy must be executed.
^.^|scope
^.^|REQUEST

.^|body
^.^|X
|The data to push as content of the request or response body.
^.^|string
^.^|-

|===

[source, json]
.Sample
----
"policy-assign-content": {
    "scope":"REQUEST",
    "body":"Put your content here"
}
----

== Http Status Code

|===
|Code |Message

.^| ```500```
| The body content can not be transformed.

|===